import Head from 'next/head';

import Card from '@/components/Card';

import data from './data/data';
import styles from '../styles/principal.module.css';
import Button from '@/components/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ color: 'cyan', fontSize: 50, textAlign: 'center'}}>Libros</h1>
      <div className={styles.container}>
        {
          data.map(libro => (
            <Card
              data={...libro}
            />
          ))
        }
      </div>
      <Button />
    </>
  )
}
